export const REQUEST_MOVELIST:string = 'REQUEST_MOVELIST';
export type REQUEST_MOVELIST_TYPE = typeof REQUEST_MOVELIST;

export const RECEIVED_MOVELIST:string = 'RECEIVED_MOVELIST';
export type RECEIVED_MOVELIST_TYPE = typeof RECEIVED_MOVELIST;

export const UPDATING_MOVELIST:string = 'UPDATING_MOVELIST:';
export type UPDATING_MOVELIST_TYPE = typeof UPDATING_MOVELIST;

export const UPDATED_MOVELIST:string = 'UPDATED_MOVELIST';
export type UPDATED_MOVELIST_TYPE = typeof UPDATED_MOVELIST;