export const REQUEST_OVERLOOK_FOR_YARD:string = 'REQUEST_OVERLOOK_FOR_YARD';
export type REQUEST_OVERLOOK_FOR_YARD_TYPE = typeof REQUEST_OVERLOOK_FOR_YARD;
export const RECEIVED_OVERLOOK_FOR_YARD:string = 'RECEIVED_OVERLOOK_FOR_YARD';
export type RECEIVED_OVERLOOK_FOR_YARD_TYPE = typeof RECEIVED_OVERLOOK_FOR_YARD;